export interface SeedHospitalDef {
  name: string;
  type: 'Government' | 'Private' | 'Charitable' | 'Autonomous';
  tagline: string;
  address: string;
  city: string;
  state: string;
  pincode: string;
  latitude: number;
  longitude: number;
  phone: string;
  emergencyPhone: string;
  email: string;
  website: string;
  workingHours: string;
  emergencyAvailable: boolean;
  totalBeds: number;
  availableBeds: number;
  specialistAvailable: boolean;
  diagnosticFacilities: string[];
  languagesSupported: string[];
  averageWaitTimeMinutes: number;
  rating: number;
  departments: {
    name: string;
    description: string;
    headDoctorName: string;
    opdDays: string[];
    opdTimings: string;
    dailyTokenCapacity: number;
    availableTokensToday: number;
    consultationFee: number;
  }[];
}

export const SEED_HOSPITALS: SeedHospitalDef[] = [
  {
    name: 'Civil Hospital Phagwara (Government 24/7)',
    type: 'Government',
    tagline: 'Premier 100-Bed Sub-Divisional Civil Hospital with 24/7 Emergency & ICU',
    address: 'GT Road, Near Central Bus Stand',
    city: 'Phagwara',
    state: 'Punjab',
    pincode: '144401',
    latitude: 31.2229,
    longitude: 75.7725,
    phone: '01824-220025',
    emergencyPhone: '108 / 01824-220108',
    email: 'smo.phagwara@punjabhealth.gov.in',
    website: 'https://nhm.punjab.gov.in',
    workingHours: '24/7 Emergency | OPD: 08:00 AM - 02:00 PM (Mon-Sat)',
    emergencyAvailable: true,
    totalBeds: 120,
    availableBeds: 34,
    specialistAvailable: true,
    diagnosticFacilities: ['Digital X-Ray', 'Ultrasound', 'Auto-Analyzer Pathology', 'Blood Storage Unit', 'ECG', 'Trauma ICU'],
    languagesSupported: ['Punjabi', 'Hindi', 'English'],
    averageWaitTimeMinutes: 20,
    rating: 4.5,
    departments: [
      {
        name: 'General Medicine',
        description: 'Comprehensive adult outpatient diagnostics and chronic disease management.',
        headDoctorName: 'Dr. Gurpreet Singh, MD Medicine',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '08:00 AM - 02:00 PM',
        dailyTokenCapacity: 90,
        availableTokensToday: 38,
        consultationFee: 10,
      },
      {
        name: 'Emergency & Trauma',
        description: '24/7 acute trauma triage, resuscitation bay, and emergency stabilization.',
        headDoctorName: 'Dr. Kamaljit Singh, MS Surgery',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
        opdTimings: '24/7 Round the Clock',
        dailyTokenCapacity: 100,
        availableTokensToday: 45,
        consultationFee: 0,
      },
      {
        name: 'Orthopedics',
        description: 'Fracture management, spinal assessment, arthritis clinic and cast application.',
        headDoctorName: 'Dr. Raman Chawla, MS Ortho',
        opdDays: ['Monday', 'Wednesday', 'Friday'],
        opdTimings: '08:30 AM - 01:30 PM',
        dailyTokenCapacity: 60,
        availableTokensToday: 22,
        consultationFee: 10,
      },
      {
        name: 'Obstetrics & Gynaecology',
        description: 'Maternal health, institutional delivery wing, antenatal checks and newborn care.',
        headDoctorName: 'Dr. Manpreet Kaur, MD OBG',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '08:30 AM - 02:00 PM',
        dailyTokenCapacity: 80,
        availableTokensToday: 29,
        consultationFee: 0,
      },
      {
        name: 'Pediatrics',
        description: 'Child wellness, universal immunization, and neonatal care.',
        headDoctorName: 'Dr. Simranjit Bhasin, MD Paed',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '09:00 AM - 02:00 PM',
        dailyTokenCapacity: 70,
        availableTokensToday: 31,
        consultationFee: 0,
      },
    ],
  },
  {
    name: 'Gandhi Hospital (P) Ltd (Multi-Speciality)',
    type: 'Private',
    tagline: 'Leading Multi-Speciality Center with Advanced Laparoscopy & Critical Care',
    address: 'NH44, Tibbi, Near Sugar Mill Crossing',
    city: 'Phagwara',
    state: 'Punjab',
    pincode: '144401',
    latitude: 31.2185,
    longitude: 75.768,
    phone: '01824-500100',
    emergencyPhone: '01824-500112',
    email: 'info@gandhihospitalphagwara.com',
    website: 'https://gandhihospitalphagwara.com',
    workingHours: '24/7 Emergency & Inpatient Services',
    emergencyAvailable: true,
    totalBeds: 85,
    availableBeds: 24,
    specialistAvailable: true,
    diagnosticFacilities: ['Multi-Slice CT', 'Digital X-Ray', 'High-Res Sonography', 'ICU/CCU', 'Fully Automated Lab'],
    languagesSupported: ['Punjabi', 'Hindi', 'English'],
    averageWaitTimeMinutes: 15,
    rating: 4.6,
    departments: [
      {
        name: 'Cardiology',
        description: 'Echo, TMT, Holter, preventative cardiology and cardiac ICU monitoring.',
        headDoctorName: 'Dr. Harvinder Sodhi, DM Cardio',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '09:30 AM - 03:30 PM',
        dailyTokenCapacity: 45,
        availableTokensToday: 16,
        consultationFee: 400,
      },
      {
        name: 'General & Laparoscopic Surgery',
        description: 'Minimally invasive keyhole surgery, hernia clinic, and acute abdominal care.',
        headDoctorName: 'Dr. S. K. Gandhi, MS Surgery',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '10:00 AM - 04:00 PM',
        dailyTokenCapacity: 50,
        availableTokensToday: 20,
        consultationFee: 350,
      },
      {
        name: 'Orthopedics & Joint Replacement',
        description: 'Knee and hip replacement, arthroscopy, and sports trauma management.',
        headDoctorName: 'Dr. Ankit Gandhi, MS Ortho',
        opdDays: ['Monday', 'Tuesday', 'Thursday', 'Saturday'],
        opdTimings: '10:30 AM - 03:00 PM',
        dailyTokenCapacity: 40,
        availableTokensToday: 14,
        consultationFee: 400,
      },
    ],
  },
  {
    name: 'Guru Nanak Mission Hospital',
    type: 'Charitable',
    tagline: 'Affordable World-Class Tertiary & Community Healthcare Mission',
    address: 'Banga-Phagwara Highway, Dahan Kaleran',
    city: 'Phagwara',
    state: 'Punjab',
    pincode: '144505',
    latitude: 31.205,
    longitude: 75.82,
    phone: '01823-250001',
    emergencyPhone: '01823-250100',
    email: 'care@gnmhospital.org',
    website: 'https://gnmhospital.org',
    workingHours: '24/7 Emergency, Dialysis & Trauma Services',
    emergencyAvailable: true,
    totalBeds: 250,
    availableBeds: 62,
    specialistAvailable: true,
    diagnosticFacilities: ['1.5T MRI', '128-Slice CT', 'Dialysis Wing (24 Beds)', 'Advanced NICU', 'Blood Bank'],
    languagesSupported: ['Punjabi', 'Hindi', 'English'],
    averageWaitTimeMinutes: 18,
    rating: 4.7,
    departments: [
      {
        name: 'General Medicine',
        description: 'Comprehensive inpatient and outpatient medical care at subsidized charges.',
        headDoctorName: 'Dr. Balwinder Singh, MD',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '09:00 AM - 03:00 PM',
        dailyTokenCapacity: 80,
        availableTokensToday: 35,
        consultationFee: 50,
      },
      {
        name: 'Nephrology & Dialysis',
        description: 'Round-the-clock hemodialysis and chronic kidney disease management.',
        headDoctorName: 'Dr. Jaspreet Sandhu, DM Nephro',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '08:00 AM - 04:00 PM',
        dailyTokenCapacity: 40,
        availableTokensToday: 18,
        consultationFee: 100,
      },
    ],
  },
  {
    name: 'Patel Hospital & Heart Institute',
    type: 'Private',
    tagline: 'NABH Accredited Comprehensive Super-Speciality & Cancer Care Center',
    address: 'Civil Lines, Near BMC Chowk',
    city: 'Jalandhar',
    state: 'Punjab',
    pincode: '144001',
    latitude: 31.326,
    longitude: 75.5762,
    phone: '0181-5241000',
    emergencyPhone: '0181-5241108',
    email: 'contact@patelhospital.com',
    website: 'https://patelhospital.com',
    workingHours: '24/7 Emergency & ICU Services',
    emergencyAvailable: true,
    totalBeds: 250,
    availableBeds: 48,
    specialistAvailable: true,
    diagnosticFacilities: ['PET-CT', 'Linear Accelerator', '3T MRI', 'Cath Lab', 'Level-3 ICU', 'NABL Lab'],
    languagesSupported: ['Punjabi', 'Hindi', 'English'],
    averageWaitTimeMinutes: 15,
    rating: 4.8,
    departments: [
      {
        name: 'Cardiology',
        description: 'Primary angioplasty, pacemaker implants, and advanced cardiac failure clinic.',
        headDoctorName: 'Dr. B. S. Bhatia, DM Cardio',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '09:00 AM - 04:00 PM',
        dailyTokenCapacity: 50,
        availableTokensToday: 19,
        consultationFee: 600,
      },
      {
        name: 'Medical Oncology',
        description: 'Chemotherapy day care, immunotherapy, and targeted molecular therapies.',
        headDoctorName: 'Dr. Shamit Chopra, DNB Oncology',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
        opdTimings: '10:00 AM - 03:00 PM',
        dailyTokenCapacity: 35,
        availableTokensToday: 12,
        consultationFee: 700,
      },
    ],
  },
  {
    name: 'Rajendra Institute of Medical Sciences (RIMS - Govt)',
    type: 'Government',
    tagline: 'Premier 1500-Bed Tertiary Care & Medical University',
    address: 'Bariatu Road, Medical College Campus',
    city: 'Ranchi',
    state: 'Jharkhand',
    pincode: '834009',
    latitude: 23.3768,
    longitude: 85.3482,
    phone: '0651-2541533',
    emergencyPhone: '108 / 0651-2541533',
    email: 'admissions@rimsranchi.org',
    website: 'https://rimsranchi.ac.in',
    workingHours: '24/7 Emergency | OPD: 08:30 AM - 03:00 PM (Mon-Sat)',
    emergencyAvailable: true,
    totalBeds: 1500,
    availableBeds: 184,
    specialistAvailable: true,
    diagnosticFacilities: ['Digital X-Ray', '128-Slice CT Scan', '3.0T MRI', 'Pathology Core', 'Blood Bank', 'Cath Lab', 'Ultrasound'],
    languagesSupported: ['English', 'Hindi', 'Santali', 'Nagpuri', 'Bengali'],
    averageWaitTimeMinutes: 45,
    rating: 4.4,
    departments: [
      {
        name: 'General Medicine',
        description: 'Comprehensive adult outpatient diagnostics and chronic disease management.',
        headDoctorName: 'Dr. J. K. Mitra, MD',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '08:30 AM - 02:30 PM',
        dailyTokenCapacity: 120,
        availableTokensToday: 42,
        consultationFee: 10,
      },
      {
        name: 'Cardiology',
        description: 'Advanced interventional cardiology, 24/7 STEMI coronary care and echocardiography.',
        headDoctorName: 'Dr. Hemant Narayan, DM Cardiology',
        opdDays: ['Monday', 'Wednesday', 'Friday'],
        opdTimings: '09:00 AM - 01:00 PM',
        dailyTokenCapacity: 60,
        availableTokensToday: 18,
        consultationFee: 20,
      },
      {
        name: 'Orthopedics',
        description: 'Trauma management, joint reconstruction, spinal care and fracture clinic.',
        headDoctorName: 'Dr. L. B. Prasad, MS Ortho',
        opdDays: ['Tuesday', 'Thursday', 'Saturday'],
        opdTimings: '09:00 AM - 02:00 PM',
        dailyTokenCapacity: 80,
        availableTokensToday: 25,
        consultationFee: 10,
      },
      {
        name: 'Obstetrics & Gynecology',
        description: 'High-risk maternity unit, neonatal triage and maternal welfare schemes.',
        headDoctorName: 'Dr. Shashi Bala, MD OBG',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '08:30 AM - 02:30 PM',
        dailyTokenCapacity: 100,
        availableTokensToday: 30,
        consultationFee: 0,
      },
      {
        name: 'Pediatrics',
        description: 'Child wellness, vaccination drives, and pediatric intensive care.',
        headDoctorName: 'Dr. A. K. Choudhary, MD Pediatrics',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '09:00 AM - 02:00 PM',
        dailyTokenCapacity: 90,
        availableTokensToday: 35,
        consultationFee: 0,
      },
    ],
  },
  {
    name: 'Sadar District Hospital',
    type: 'Government',
    tagline: 'District Headquarters Public Hospital with Free Essential Diagnostics',
    address: 'Purulia Road, Ahirtoli',
    city: 'Ranchi',
    state: 'Jharkhand',
    pincode: '834001',
    latitude: 23.3644,
    longitude: 85.3289,
    phone: '0651-2200321',
    emergencyPhone: '102 / 0651-2200322',
    email: 'sadarhosp.ranchi@jharkhand.gov.in',
    website: 'https://ranchi.nic.in/sadar-hospital',
    workingHours: '24/7 Emergency & Maternity | OPD: 09:00 AM - 02:00 PM',
    emergencyAvailable: true,
    totalBeds: 500,
    availableBeds: 72,
    specialistAvailable: true,
    diagnosticFacilities: ['Digital X-Ray', 'Ultrasound', 'Pathology Lab', 'ECG', 'Dialysis Unit'],
    languagesSupported: ['Hindi', 'Santali', 'Mundari', 'Kurukh', 'English'],
    averageWaitTimeMinutes: 30,
    rating: 4.1,
    departments: [
      {
        name: 'General Medicine',
        description: 'Primary triage and non-communicable disease (NCD) screening.',
        headDoctorName: 'Dr. Vivek Sinha, MD',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '09:00 AM - 02:00 PM',
        dailyTokenCapacity: 100,
        availableTokensToday: 55,
        consultationFee: 0,
      },
      {
        name: 'Ophthalmology',
        description: 'Cataract screening, refractive corrections, and vision testing.',
        headDoctorName: 'Dr. Meena Kumari, MS Ophth',
        opdDays: ['Monday', 'Wednesday', 'Friday'],
        opdTimings: '09:00 AM - 01:00 PM',
        dailyTokenCapacity: 50,
        availableTokensToday: 22,
        consultationFee: 0,
      },
      {
        name: 'Pulmonology & DOTS Center',
        description: 'Tuberculosis and respiratory illness diagnostic center.',
        headDoctorName: 'Dr. S. K. Singh, DTCD',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '09:00 AM - 01:30 PM',
        dailyTokenCapacity: 60,
        availableTokensToday: 30,
        consultationFee: 0,
      },
    ],
  },
  {
    name: 'Apollo Super Speciality Hospital',
    type: 'Private',
    tagline: 'JCI-Accredited Multi-Organ Center of Excellence',
    address: 'Lake Road, Main Road Crossing',
    city: 'Ranchi',
    state: 'Jharkhand',
    pincode: '834001',
    latitude: 23.3551,
    longitude: 85.3121,
    phone: '0651-6600555',
    emergencyPhone: '1066 / 0651-6600500',
    email: 'contact@apollohospitalsranchi.com',
    website: 'https://apollohospitals.com/ranchi',
    workingHours: '24/7 Emergency, Trauma & Critical Care',
    emergencyAvailable: true,
    totalBeds: 350,
    availableBeds: 58,
    specialistAvailable: true,
    diagnosticFacilities: ['PET-CT', '3T MRI', 'Biplane Cath Lab', 'Robotic Surgery', 'Molecular Pathology', 'ECMO'],
    languagesSupported: ['English', 'Hindi', 'Bengali', 'Odia'],
    averageWaitTimeMinutes: 15,
    rating: 4.8,
    departments: [
      {
        name: 'Cardiology',
        description: 'Comprehensive cardiac surgery, electrophysiology, and angiographies.',
        headDoctorName: 'Dr. Rajiv Anand, MD DM',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '10:00 AM - 04:00 PM',
        dailyTokenCapacity: 45,
        availableTokensToday: 12,
        consultationFee: 800,
      },
      {
        name: 'Neurology & Neurosurgery',
        description: 'Stroke triage unit, neuro-trauma, and spine micro-surgery.',
        headDoctorName: 'Dr. P. K. Srivastava, MCh Neuro',
        opdDays: ['Monday', 'Wednesday', 'Friday'],
        opdTimings: '10:00 AM - 03:00 PM',
        dailyTokenCapacity: 35,
        availableTokensToday: 8,
        consultationFee: 900,
      },
      {
        name: 'Oncology',
        description: 'Medical, surgical, and linear accelerator radiation oncology.',
        headDoctorName: 'Dr. Renu Verma, MD Oncology',
        opdDays: ['Tuesday', 'Thursday', 'Saturday'],
        opdTimings: '11:00 AM - 04:00 PM',
        dailyTokenCapacity: 40,
        availableTokensToday: 15,
        consultationFee: 850,
      },
    ],
  },
  {
    name: 'Medanta Abdur Razzaque Ansari Memorial Hospital',
    type: 'Private',
    tagline: 'Comprehensive Heart & Multi-Speciality Institute in Sub-Urban Belt',
    address: 'NH-33, Irba, Ormanjhi',
    city: 'Ranchi',
    state: 'Jharkhand',
    pincode: '835219',
    latitude: 23.4862,
    longitude: 85.4719,
    phone: '0651-7123100',
    emergencyPhone: '0651-7123999',
    email: 'info@medantaranchi.org',
    website: 'https://medanta.org/ranchi',
    workingHours: '24/7 Emergency & ICU Care',
    emergencyAvailable: true,
    totalBeds: 400,
    availableBeds: 82,
    specialistAvailable: true,
    diagnosticFacilities: ['CT Angio', 'Cardiac MRI', 'Nuclear Medicine', 'Level-3 NICU', 'Blood Bank'],
    languagesSupported: ['Hindi', 'Urdu', 'English', 'Santali'],
    averageWaitTimeMinutes: 20,
    rating: 4.6,
    departments: [
      {
        name: 'Cardiology',
        description: 'Cardiac bypass surgery, stent placement, and heart failure clinic.',
        headDoctorName: 'Dr. M. S. Akhtar, MCh Cardio',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '09:30 AM - 04:30 PM',
        dailyTokenCapacity: 50,
        availableTokensToday: 20,
        consultationFee: 750,
      },
      {
        name: 'Nephrology & Dialysis',
        description: 'Kidney disease management, renal transplant unit, and 24-bed dialysis floor.',
        headDoctorName: 'Dr. T. N. Roy, DM Nephro',
        opdDays: ['Monday', 'Wednesday', 'Friday'],
        opdTimings: '10:00 AM - 03:00 PM',
        dailyTokenCapacity: 30,
        availableTokensToday: 10,
        consultationFee: 700,
      },
    ],
  },
  {
    name: 'Paras Healthcare HEC Medical Complex',
    type: 'Private',
    tagline: 'State-of-the-Art Multi-Speciality Hospital in South Urban Zone',
    address: 'Sector-3, HEC Colony, Dhurwa',
    city: 'Ranchi',
    state: 'Jharkhand',
    pincode: '834004',
    latitude: 23.3082,
    longitude: 85.2891,
    phone: '0651-7100000',
    emergencyPhone: '0651-7100100',
    email: 'ranchi@parashospitals.com',
    website: 'https://parashospitals.com/paras-ranchi',
    workingHours: '24/7 Emergency & Critical Care',
    emergencyAvailable: true,
    totalBeds: 300,
    availableBeds: 64,
    specialistAvailable: true,
    diagnosticFacilities: ['CT Scan', '1.5T MRI', 'Automated Lab', 'Endoscopy Suite', 'Ultrasound'],
    languagesSupported: ['Hindi', 'English', 'Bengali'],
    averageWaitTimeMinutes: 25,
    rating: 4.5,
    departments: [
      {
        name: 'General Medicine',
        description: 'Internal medicine and lifestyle disease outpatient consultations.',
        headDoctorName: 'Dr. Sanjay Agarwal, MD',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '09:00 AM - 03:00 PM',
        dailyTokenCapacity: 60,
        availableTokensToday: 24,
        consultationFee: 500,
      },
      {
        name: 'Orthopedics',
        description: 'Arthroscopy, trauma surgery, and spine rehabilitation.',
        headDoctorName: 'Dr. Deepak Verma, MS Ortho',
        opdDays: ['Monday', 'Wednesday', 'Friday'],
        opdTimings: '10:00 AM - 02:00 PM',
        dailyTokenCapacity: 40,
        availableTokensToday: 16,
        consultationFee: 600,
      },
    ],
  },
  {
    name: 'Devkamal Multispeciality Hospital',
    type: 'Charitable',
    tagline: 'Accessible Burn Care, Plastic Surgery & Reconstructive Center',
    address: 'Bajra, Ratu Road',
    city: 'Ranchi',
    state: 'Jharkhand',
    pincode: '834005',
    latitude: 23.3821,
    longitude: 85.2754,
    phone: '0651-2512133',
    emergencyPhone: '0651-2512144',
    email: 'info@devkamalhospital.com',
    website: 'https://devkamalhospital.org',
    workingHours: '24/7 Trauma, Burns & Emergency',
    emergencyAvailable: true,
    totalBeds: 180,
    availableBeds: 38,
    specialistAvailable: true,
    diagnosticFacilities: ['X-Ray', 'Ultrasound', 'Burns ICU', 'Clinical Biochemistry Lab'],
    languagesSupported: ['Hindi', 'Santali', 'Ho', 'English'],
    averageWaitTimeMinutes: 20,
    rating: 4.3,
    departments: [
      {
        name: 'General Medicine',
        description: 'General outpatient diagnostics and post-injury recovery.',
        headDoctorName: 'Dr. Subhash Bose, MD',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '09:00 AM - 03:00 PM',
        dailyTokenCapacity: 50,
        availableTokensToday: 30,
        consultationFee: 150,
      },
    ],
  },
  {
    name: 'Ramgarh Community Health Center',
    type: 'Government',
    tagline: 'Primary & Secondary Rural Health Hub with Maternal Care',
    address: 'Chitarpur Road, Block B',
    city: 'Ramgarh',
    state: 'Jharkhand',
    pincode: '829101',
    latitude: 23.6312,
    longitude: 85.5143,
    phone: '06553-222110',
    emergencyPhone: '108',
    email: 'chc.ramgarh@jharkhand.gov.in',
    website: 'https://ramgarh.nic.in/health',
    workingHours: '24/7 Delivery Room & Emergency | OPD: 09:00 AM - 01:00 PM',
    emergencyAvailable: true,
    totalBeds: 60,
    availableBeds: 14,
    specialistAvailable: false,
    diagnosticFacilities: ['Basic Pathology Lab', 'Routine X-Ray', 'ECG'],
    languagesSupported: ['Hindi', 'Santali', 'Khortha'],
    averageWaitTimeMinutes: 15,
    rating: 3.9,
    departments: [
      {
        name: 'General Medicine',
        description: 'First-contact triage, fever clinic, and rapid malaria/dengue testing.',
        headDoctorName: 'Dr. R. P. Mahato, MBBS',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '09:00 AM - 01:00 PM',
        dailyTokenCapacity: 70,
        availableTokensToday: 35,
        consultationFee: 0,
      },
    ],
  },
  {
    name: 'Khunti Sub-Divisional Hospital',
    type: 'Government',
    tagline: 'Tribal Belt Public Healthcare & Malaria Screening Center',
    address: 'Court Road, Main Bazaar',
    city: 'Khunti',
    state: 'Jharkhand',
    pincode: '835210',
    latitude: 23.0745,
    longitude: 85.2798,
    phone: '06528-220105',
    emergencyPhone: '108',
    email: 'sdh.khunti@jharkhand.gov.in',
    website: 'https://khunti.nic.in/health',
    workingHours: '24/7 Emergency & Maternity',
    emergencyAvailable: true,
    totalBeds: 100,
    availableBeds: 24,
    specialistAvailable: true,
    diagnosticFacilities: ['Digital X-Ray', 'Ultrasound', 'Sickle Cell Testing Lab', 'DOTS Center'],
    languagesSupported: ['Mundari', 'Santali', 'Hindi', 'Ho'],
    averageWaitTimeMinutes: 20,
    rating: 4.0,
    departments: [
      {
        name: 'General Medicine',
        description: 'Rural community clinic and nutritional deficiency monitoring.',
        headDoctorName: 'Dr. S. Munda, MD',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '09:00 AM - 01:30 PM',
        dailyTokenCapacity: 80,
        availableTokensToday: 40,
        consultationFee: 0,
      },
    ],
  },
  {
    name: 'Lohardaga Referral Hospital',
    type: 'Government',
    tagline: 'Western District Triage & Maternal Health Center',
    address: 'Near Collectorate, Ranchi-Gumla Highway',
    city: 'Lohardaga',
    state: 'Jharkhand',
    pincode: '835302',
    latitude: 23.4421,
    longitude: 84.6812,
    phone: '06526-224012',
    emergencyPhone: '108',
    email: 'rh.lohardaga@jharkhand.gov.in',
    website: 'https://lohardaga.nic.in/health',
    workingHours: '24/7 Emergency & Primary Care',
    emergencyAvailable: true,
    totalBeds: 120,
    availableBeds: 32,
    specialistAvailable: true,
    diagnosticFacilities: ['Routine Pathology', 'X-Ray', 'Ultrasound'],
    languagesSupported: ['Kurukh', 'Hindi', 'Nagpuri'],
    averageWaitTimeMinutes: 25,
    rating: 3.8,
    departments: [
      {
        name: 'General Medicine',
        description: 'Outpatient consultations and snakebite venom treatment center.',
        headDoctorName: 'Dr. B. Oraon, MBBS DCH',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '09:00 AM - 02:00 PM',
        dailyTokenCapacity: 75,
        availableTokensToday: 30,
        consultationFee: 0,
      },
    ],
  },
  {
    name: 'Hazaribagh District Memorial Hospital',
    type: 'Government',
    tagline: 'Northern Regional Public Referral Hospital',
    address: 'Matwari, Near Old Bus Stand',
    city: 'Hazaribagh',
    state: 'Jharkhand',
    pincode: '825301',
    latitude: 23.9921,
    longitude: 85.3641,
    phone: '06546-222045',
    emergencyPhone: '108 / 06546-222046',
    email: 'dmh.hazaribagh@jharkhand.gov.in',
    website: 'https://hazaribag.nic.in/health',
    workingHours: '24/7 Emergency & Trauma Care',
    emergencyAvailable: true,
    totalBeds: 300,
    availableBeds: 62,
    specialistAvailable: true,
    diagnosticFacilities: ['CT Scan', 'Digital X-Ray', 'Pathology Lab', 'Blood Bank', 'Ultrasound'],
    languagesSupported: ['Hindi', 'Khortha', 'Urdu', 'English'],
    averageWaitTimeMinutes: 35,
    rating: 4.2,
    departments: [
      {
        name: 'General Medicine',
        description: 'Primary medical care and non-communicable disease clinic.',
        headDoctorName: 'Dr. P. K. Barnwal, MD',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '08:30 AM - 02:00 PM',
        dailyTokenCapacity: 90,
        availableTokensToday: 35,
        consultationFee: 0,
      },
      {
        name: 'Orthopedics',
        description: 'Trauma care, fracture treatment, and joint consultations.',
        headDoctorName: 'Dr. R. S. Pandey, MS Ortho',
        opdDays: ['Monday', 'Wednesday', 'Friday'],
        opdTimings: '09:00 AM - 01:30 PM',
        dailyTokenCapacity: 50,
        availableTokensToday: 18,
        consultationFee: 0,
      },
    ],
  },
  {
    name: 'Orchid Medical Center',
    type: 'Private',
    tagline: 'NABH-Accredited Multi-Speciality Center in Core City',
    address: 'H.B. Road, Ahirtoli',
    city: 'Ranchi',
    state: 'Jharkhand',
    pincode: '834001',
    latitude: 23.3688,
    longitude: 85.3341,
    phone: '0651-7100100',
    emergencyPhone: '0651-7100111',
    email: 'info@orchidmedcentre.com',
    website: 'https://orchidmedcentre.com',
    workingHours: '24/7 Critical Care & Emergency',
    emergencyAvailable: true,
    totalBeds: 200,
    availableBeds: 35,
    specialistAvailable: true,
    diagnosticFacilities: ['1.5T MRI', '64-Slice CT', 'Cath Lab', 'Dialysis', 'Pathology'],
    languagesSupported: ['English', 'Hindi', 'Bengali'],
    averageWaitTimeMinutes: 20,
    rating: 4.5,
    departments: [
      {
        name: 'Cardiology',
        description: 'Non-invasive and interventional heart care.',
        headDoctorName: 'Dr. S. K. Goel, DM Cardio',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '10:00 AM - 04:00 PM',
        dailyTokenCapacity: 40,
        availableTokensToday: 14,
        consultationFee: 650,
      },
    ],
  },
  {
    name: 'Guru Nanak Hospital & Research Center',
    type: 'Charitable',
    tagline: 'Affordable Community-Centric Charitable Healthcare',
    address: 'Station Road, Near Ranchi Railway Station',
    city: 'Ranchi',
    state: 'Jharkhand',
    pincode: '834001',
    latitude: 23.3512,
    longitude: 85.3419,
    phone: '0651-2460111',
    emergencyPhone: '0651-2460112',
    email: 'admin@gurunanakhospital.org',
    website: 'https://gurunanakhospital.org',
    workingHours: '24/7 Emergency & General OPD',
    emergencyAvailable: true,
    totalBeds: 150,
    availableBeds: 30,
    specialistAvailable: true,
    diagnosticFacilities: ['Digital X-Ray', 'Ultrasound', 'Biochemistry Lab', 'ECG'],
    languagesSupported: ['Hindi', 'Punjabi', 'Bengali', 'English'],
    averageWaitTimeMinutes: 25,
    rating: 4.2,
    departments: [
      {
        name: 'General Medicine',
        description: 'Subsidized general outpatient care and diabetes management.',
        headDoctorName: 'Dr. G. S. Bhatia, MD',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '09:00 AM - 03:00 PM',
        dailyTokenCapacity: 60,
        availableTokensToday: 25,
        consultationFee: 100,
      },
    ],
  },
  {
    name: 'Civil Hospital Phagwara (Govt Sub-Divisional Hospital)',
    type: 'Government',
    tagline: '120-Bed Comprehensive Community Health & 24/7 Trauma Emergency',
    address: 'Grand Trunk Road, Subhash Nagar',
    city: 'Phagwara',
    state: 'Punjab',
    pincode: '144401',
    latitude: 31.2238,
    longitude: 75.7708,
    phone: '01824-260230',
    emergencyPhone: '108 / 01824-260231',
    email: 'civilhospital.phagwara@punjab.gov.in',
    website: 'https://kapurthala.nic.in/health',
    workingHours: '24/7 Emergency & Maternity • OPD: 08:30 AM - 02:30 PM (Mon-Sat)',
    emergencyAvailable: true,
    totalBeds: 120,
    availableBeds: 38,
    specialistAvailable: true,
    diagnosticFacilities: ['Digital X-Ray', 'Ultrasound & Color Doppler', 'Automated Pathology Lab', 'ECG', 'Trauma Ward', 'Blood Storage'],
    languagesSupported: ['Punjabi', 'Hindi', 'English'],
    averageWaitTimeMinutes: 20,
    rating: 4.3,
    departments: [
      {
        name: 'General Medicine',
        description: 'Comprehensive adult outpatient diagnostics, diabetes care, and fever clinic.',
        headDoctorName: 'Dr. Gurpreet Singh, MD (Medicine)',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '08:30 AM - 02:00 PM',
        dailyTokenCapacity: 80,
        availableTokensToday: 34,
        consultationFee: 10,
      },
      {
        name: 'Obstetrics & Gynecology',
        description: 'Maternal health, high-risk delivery ward, and Ayushman Bharat PM-JAY cashless maternity.',
        headDoctorName: 'Dr. Harpreet Kaur, MD (OBG)',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '08:30 AM - 02:00 PM',
        dailyTokenCapacity: 60,
        availableTokensToday: 22,
        consultationFee: 0,
      },
      {
        name: 'Orthopedics',
        description: 'Accident trauma stabilization, fracture plastering, arthritis and joint care.',
        headDoctorName: 'Dr. Manmohan Sharma, MS (Ortho)',
        opdDays: ['Monday', 'Wednesday', 'Friday'],
        opdTimings: '09:00 AM - 01:30 PM',
        dailyTokenCapacity: 50,
        availableTokensToday: 19,
        consultationFee: 10,
      },
      {
        name: 'Pediatrics',
        description: 'Infant care, neonatal triage, and universal immunization vaccines.',
        headDoctorName: 'Dr. Ravinder Bhasin, MD (Pediatrics)',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '09:00 AM - 02:00 PM',
        dailyTokenCapacity: 55,
        availableTokensToday: 26,
        consultationFee: 0,
      },
      {
        name: 'Cardiology',
        description: 'Cardiac emergency triage, ECG, hypertension monitoring and referral dispatch.',
        headDoctorName: 'Dr. Amritpal Sidhu, MD Medicine (Cardiology Fellow)',
        opdDays: ['Tuesday', 'Thursday', 'Saturday'],
        opdTimings: '09:00 AM - 01:00 PM',
        dailyTokenCapacity: 40,
        availableTokensToday: 18,
        consultationFee: 10,
      },
    ],
  },
  {
    name: 'Tagore Hospital & Heart Care Centre',
    type: 'Private',
    tagline: 'NABH-Accredited 250-Bed Premier Cardiac & Multi-Speciality Institute',
    address: 'Mahavir Marg, Near BMC Chowk',
    city: 'Jalandhar',
    state: 'Punjab',
    pincode: '144001',
    latitude: 31.3260,
    longitude: 75.5762,
    phone: '0181-2242400',
    emergencyPhone: '0181-2242401 / 98140-55555',
    email: 'info@tagorehospital.net',
    website: 'https://tagorehospital.net',
    workingHours: '24/7 Coronary Intensive Care & Emergency • OPD: 09:00 AM - 05:00 PM',
    emergencyAvailable: true,
    totalBeds: 250,
    availableBeds: 54,
    specialistAvailable: true,
    diagnosticFacilities: ['Flat Panel Digital Cath Lab', '128-Slice Cardiac CT', '3.0T MRI', '2D/3D Echocardiography', 'Dialysis Centre', 'Advanced Pathology'],
    languagesSupported: ['Punjabi', 'Hindi', 'English'],
    averageWaitTimeMinutes: 15,
    rating: 4.7,
    departments: [
      {
        name: 'Cardiology',
        description: 'Primary angioplasty, pacemaker implantation, structural heart and heart failure clinic.',
        headDoctorName: 'Dr. Raman Chawla, MD, DM (Cardiology), FACC',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '09:30 AM - 04:00 PM',
        dailyTokenCapacity: 70,
        availableTokensToday: 28,
        consultationFee: 600,
      },
      {
        name: 'Cardiothoracic Surgery',
        description: 'Minimally invasive CABG bypass surgery, valve replacement, and thoracic repairs.',
        headDoctorName: 'Dr. Vijay Mahajan, MS, MCh (CTVS)',
        opdDays: ['Monday', 'Wednesday', 'Friday'],
        opdTimings: '10:00 AM - 03:00 PM',
        dailyTokenCapacity: 30,
        availableTokensToday: 12,
        consultationFee: 800,
      },
      {
        name: 'Nephrology & Dialysis',
        description: 'Hemodialysis, acute kidney injury management, and renal transplant prep.',
        headDoctorName: 'Dr. Amanpreet Singh, MD, DM (Nephrology)',
        opdDays: ['Monday', 'Tuesday', 'Thursday', 'Saturday'],
        opdTimings: '10:00 AM - 02:00 PM',
        dailyTokenCapacity: 40,
        availableTokensToday: 16,
        consultationFee: 500,
      },
      {
        name: 'General Medicine',
        description: 'Internal medicine, infectious diseases, and diabetes metabolic care.',
        headDoctorName: 'Dr. S. K. Sharma, MD (Medicine)',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '09:00 AM - 03:00 PM',
        dailyTokenCapacity: 60,
        availableTokensToday: 24,
        consultationFee: 400,
      },
    ],
  },
  {
    name: 'Patel Hospital (Cancer & Multi-Speciality Institute)',
    type: 'Private',
    tagline: 'Comprehensive Oncology, Surgery & 300-Bed Critical Care Centre',
    address: 'Civil Lines, Near BMC Chowk',
    city: 'Jalandhar',
    state: 'Punjab',
    pincode: '144001',
    latitude: 31.3195,
    longitude: 75.5890,
    phone: '0181-5241000',
    emergencyPhone: '0181-5241100',
    email: 'contact@patelhospital.com',
    website: 'https://patelhospital.com',
    workingHours: '24/7 Emergency & ICU • OPD: 09:00 AM - 05:30 PM',
    emergencyAvailable: true,
    totalBeds: 300,
    availableBeds: 68,
    specialistAvailable: true,
    diagnosticFacilities: ['PET-CT Scanner', 'Linear Accelerator (LINAC)', '1.5T MRI', 'Digital Mammography', 'Video Endoscopy', 'Histopathology Lab'],
    languagesSupported: ['Punjabi', 'Hindi', 'English'],
    averageWaitTimeMinutes: 20,
    rating: 4.6,
    departments: [
      {
        name: 'Oncology',
        description: 'Chemotherapy day-care, targeted immunotherapy, and radiation oncology.',
        headDoctorName: 'Dr. B. S. Chopra, MD, DNB (Medical Oncology)',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '09:30 AM - 04:30 PM',
        dailyTokenCapacity: 50,
        availableTokensToday: 21,
        consultationFee: 700,
      },
      {
        name: 'Gastroenterology',
        description: 'Endoscopy, colonoscopy, ERCP, and liver cirrhosis interventions.',
        headDoctorName: 'Dr. Rajesh Gupta, MD, DM (Gastroenterology)',
        opdDays: ['Monday', 'Tuesday', 'Thursday', 'Saturday'],
        opdTimings: '10:00 AM - 03:00 PM',
        dailyTokenCapacity: 45,
        availableTokensToday: 17,
        consultationFee: 650,
      },
      {
        name: 'Orthopedics & Spine',
        description: 'Robotic knee/hip replacement, arthroscopy, and minimally invasive spine surgery.',
        headDoctorName: 'Dr. Kanwarjeet Singh, MS (Ortho), MCh',
        opdDays: ['Monday', 'Wednesday', 'Friday'],
        opdTimings: '09:00 AM - 02:00 PM',
        dailyTokenCapacity: 40,
        availableTokensToday: 15,
        consultationFee: 600,
      },
    ],
  },
  {
    name: 'Dayanand Medical College & Hospital (DMCH)',
    type: 'Charitable',
    tagline: '1500-Bed Apex Tertiary Care Hospital & Medical University',
    address: 'Civil Lines, Tagore Nagar',
    city: 'Ludhiana',
    state: 'Punjab',
    pincode: '141001',
    latitude: 30.9010,
    longitude: 75.8573,
    phone: '0161-4687700',
    emergencyPhone: '0161-4688888 / 108',
    email: 'principal@dmch.edu',
    website: 'https://dmch.edu',
    workingHours: '24/7 Level-1 Trauma & Emergency • OPD: 08:30 AM - 03:30 PM',
    emergencyAvailable: true,
    totalBeds: 1500,
    availableBeds: 220,
    specialistAvailable: true,
    diagnosticFacilities: ['Dual Source Cardiac CT', '3.0T MRI', 'Bi-plane Cath Lab', 'Nuclear Medicine (SPECT-CT)', 'Blood Bank & Component Lab', 'Dialysis (50 Beds)'],
    languagesSupported: ['Punjabi', 'Hindi', 'English'],
    averageWaitTimeMinutes: 35,
    rating: 4.8,
    departments: [
      {
        name: 'Cardiology',
        description: 'Hero DMC Heart Institute, electrophysiology, complex coronary angioplasty and cardiac ICU.',
        headDoctorName: 'Dr. G. S. Wander, MD, DM (Cardiology), FAMS',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '08:30 AM - 02:30 PM',
        dailyTokenCapacity: 90,
        availableTokensToday: 38,
        consultationFee: 250,
      },
      {
        name: 'Neurology & Stroke Center',
        description: 'Comprehensive acute stroke thrombolysis, epilepsy clinic, and neuro-electrophysiology.',
        headDoctorName: 'Dr. Gagandeep Singh, MD, DM (Neurology), FRCP',
        opdDays: ['Monday', 'Wednesday', 'Friday'],
        opdTimings: '09:00 AM - 02:00 PM',
        dailyTokenCapacity: 60,
        availableTokensToday: 24,
        consultationFee: 250,
      },
      {
        name: 'Orthopedics & Joint Replacement',
        description: 'Polytrauma resuscitation, joint arthroplasty, and pediatric orthopedic surgery.',
        headDoctorName: 'Dr. Rajnish Garg, MS (Ortho)',
        opdDays: ['Tuesday', 'Thursday', 'Saturday'],
        opdTimings: '09:00 AM - 02:00 PM',
        dailyTokenCapacity: 70,
        availableTokensToday: 31,
        consultationFee: 200,
      },
      {
        name: 'General Medicine',
        description: 'Subsidized adult primary care, hypertension, rheumatology, and respiratory clinics.',
        headDoctorName: 'Dr. Dinesh Gupta, MD (Medicine)',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '08:30 AM - 02:30 PM',
        dailyTokenCapacity: 120,
        availableTokensToday: 55,
        consultationFee: 150,
      },
    ],
  },
  {
    name: 'All India Institute of Medical Sciences (AIIMS)',
    type: 'Autonomous',
    tagline: 'Apex Institute of National Importance & Tertiary Super-Speciality Hospital',
    address: 'Sri Aurobindo Marg, Ansari Nagar',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110029',
    latitude: 28.5672,
    longitude: 77.2100,
    phone: '011-26588500',
    emergencyPhone: '011-26588700 / 102',
    email: 'director@aiims.edu',
    website: 'https://aiims.edu',
    workingHours: '24/7 Level-1 Trauma Emergency • OPD: 08:00 AM - 02:00 PM (Mon-Sat)',
    emergencyAvailable: true,
    totalBeds: 2500,
    availableBeds: 340,
    specialistAvailable: true,
    diagnosticFacilities: ['Robotic Surgery Unit', 'PET-MRI', 'Whole Genome Sequencing Lab', '3.0T MRI', '256-Slice CT', 'Transplant Immunology'],
    languagesSupported: ['Hindi', 'English', 'Punjabi', 'Urdu', 'Bengali'],
    averageWaitTimeMinutes: 40,
    rating: 4.9,
    departments: [
      {
        name: 'Cardiology',
        description: 'Cardiothoracic Centre (CTC), structural valve repairs, transcatheter aortic valves (TAVI).',
        headDoctorName: 'Dr. Balram Bhargava, MD, DM (Cardiology)',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '08:30 AM - 01:30 PM',
        dailyTokenCapacity: 150,
        availableTokensToday: 52,
        consultationFee: 20,
      },
      {
        name: 'Oncology (Dr. BRA IRCH)',
        description: 'National Cancer Institute, bone marrow transplants, precision targeted therapy.',
        headDoctorName: 'Dr. S. V. S. Deo, MS, MCh (Surgical Oncology)',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '08:30 AM - 02:00 PM',
        dailyTokenCapacity: 120,
        availableTokensToday: 44,
        consultationFee: 20,
      },
      {
        name: 'Neurology',
        description: 'Neurosciences Centre, deep brain stimulation, neuromuscular disorders and epilepsy monitoring.',
        headDoctorName: 'Dr. M. V. Padma Srivastava, MD, DM (Neurology)',
        opdDays: ['Monday', 'Wednesday', 'Friday'],
        opdTimings: '09:00 AM - 01:30 PM',
        dailyTokenCapacity: 90,
        availableTokensToday: 32,
        consultationFee: 20,
      },
      {
        name: 'General Medicine & Pulmonology',
        description: 'Internal medicine, infectious diseases, sleep lab, and critical respiratory care.',
        headDoctorName: 'Dr. Randeep Guleria, MD, DM (Pulmonary Medicine)',
        opdDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        opdTimings: '08:00 AM - 02:00 PM',
        dailyTokenCapacity: 180,
        availableTokensToday: 78,
        consultationFee: 10,
      },
    ],
  },
];
